version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/root/src'
    tty: true
    volumes:
      - ${SRC_PATH}:/root/src
      # FIXME これは良くないねぇ
      - .env:/root/src/.env
